#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-23.05.2

on:
  ##push:
    branches: 
      - main
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python2 python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
       
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          chmod -R 777 *
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          # cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_GZIP=y
          # CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
          # CONFIG_KERNEL_BUILD_DOMAIN="Azure"
          # EOF

          # 编译 PISEN WFR101N 固件:
          cat >> .config <<EOF
         
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_generic=y
          CONFIG_TARGET_MULTI_PROFILE=y

          # CONFIG_TARGET_DEVICE_ath79_generic_DEVICE_pisen_wfr101n=y
          CONFIG_TARGET_ath79_generic_DEVICE_pisen_wfr101n=y
          # CONFIG_TARGET_DEVICE_PACKAGES_ath79_generic_DEVICE_pisen_wfr101n=""
         
          CONFIG_ALL_KMODS=y
          CONFIG_ALL_NONSHARED=y
          CONFIG_DEVEL=y
          CONFIG_TARGET_PER_DEVICE_ROOTFS=y
          CONFIG_AUTOREMOVE=y
          CONFIG_BPF_TOOLCHAIN_BUILD_LLVM=y
          # CONFIG_BPF_TOOLCHAIN_NONE is not set
          CONFIG_BUILDBOT=y
          CONFIG_COLLECT_KERNEL_DEBUG=y
          CONFIG_HAS_BPF_TOOLCHAIN=y
          CONFIG_IB=y
          CONFIG_IMAGEOPT=y
          CONFIG_JSON_CYCLONEDX_SBOM=y
          CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
          CONFIG_KERNEL_BUILD_USER="builder"
          # CONFIG_KERNEL_KALLSYMS is not set
          CONFIG_MAKE_TOOLCHAIN=y
          CONFIG_PACKAGE_cgi-io=y
          CONFIG_PACKAGE_libbpf=m
          CONFIG_PACKAGE_libelf=m
          CONFIG_PACKAGE_liblucihttp=y
          CONFIG_PACKAGE_liblucihttp-ucode=y
          CONFIG_PACKAGE_libpcap=m
          CONFIG_PACKAGE_libxdp=m
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_luci-light=y
          CONFIG_PACKAGE_luci-mod-admin-full=y
          CONFIG_PACKAGE_luci-mod-network=y
          CONFIG_PACKAGE_luci-mod-status=y
          CONFIG_PACKAGE_luci-mod-system=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-ppp=y
          CONFIG_PACKAGE_luci-ssl=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_px5g-mbedtls=y
          CONFIG_PACKAGE_qosify=m
          CONFIG_PACKAGE_rpcd=y
          CONFIG_PACKAGE_rpcd-mod-file=y
          CONFIG_PACKAGE_rpcd-mod-iwinfo=y
          CONFIG_PACKAGE_rpcd-mod-luci=y
          CONFIG_PACKAGE_rpcd-mod-rrdns=y
          CONFIG_PACKAGE_rpcd-mod-ucode=y
          CONFIG_PACKAGE_tc-tiny=m
          CONFIG_PACKAGE_ucode-mod-html=y
          CONFIG_PACKAGE_ucode-mod-math=y
          CONFIG_PACKAGE_uhttpd=y
          CONFIG_PACKAGE_uhttpd-mod-ubus=y
          CONFIG_PACKAGE_xdp-filter=m
          CONFIG_PACKAGE_xdp-loader=m
          CONFIG_PACKAGE_xdpdump=m
          CONFIG_REPRODUCIBLE_DEBUG_INFO=y
          CONFIG_SDK=y
          CONFIG_SDK_LLVM_BPF=y
          CONFIG_TARGET_ALL_PROFILES=y
          CONFIG_USE_LLVM_BUILD=y
          CONFIG_VERSIONOPT=y
          CONFIG_VERSION_BUG_URL=""
          CONFIG_VERSION_CODE=""
          CONFIG_VERSION_DIST="OpenWrt"
          CONFIG_VERSION_FILENAMES=y
          CONFIG_VERSION_HOME_URL=""
          CONFIG_VERSION_HWREV=""
          CONFIG_VERSION_MANUFACTURER=""
          CONFIG_VERSION_MANUFACTURER_URL=""
          CONFIG_VERSION_NUMBER=""
          CONFIG_VERSION_PRODUCT=""
          CONFIG_VERSION_REPO="https://downloads.openwrt.org/releases/23.05.2"
          CONFIG_VERSION_SUPPORT_URL=""
          EOF
          
          # 常用LuCI插件选择:
          #cat >> .config <<EOF
          # CONFIG_PACKAGE_luci-app-accesscontrol=y
          # CONFIG_PACKAGE_luci-app-nft-qos=y
          # CONFIG_PACKAGE_luci-app-pptp-server=y
          # CONFIG_PACKAGE_luci-app-access_control=y
          # CONFIG_PACKAGE_luci-app-adbyby-plus=y
          # CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-kodexplorer=y
          # CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-openvpn-server=y
          # CONFIG_PACKAGE_luci-app-qbittorrent=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          # CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-v2ray-server=y
          # CONFIG_PACKAGE_luci-app-verysync=y
          # CONFIG_PACKAGE_luci-app-webadmin=y
          # CONFIG_PACKAGE_luci-app-wireguard=y
          # CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # CONFIG_PACKAGE_luci=y
          # CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          # CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
          #EOF
          
          # LuCI主题:
          #cat >> .config <<EOF
          # CONFIG_PACKAGE_luci-theme-argon=y
          # CONFIG_PACKAGE_luci-theme-netgear=y
          #CONFIG_PACKAGE_luci-theme-openwrt=y
          #EOF
          
          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
